### ISSUE TITLE
SSDT-PLUG

### ISSUE THREAD

**Issue by BeauMcMurray** [midi1996/P50-opencore-hackintosh#2]
The guide mentions to use SSDT-PLUG from this guide, not elsewhere. The file collection however does not contain SSDT-PLUG.

**Comment by midi1996** [comment]
it's a typo, I meant SSDT-XCPM. Will fix that when I have time.

**Comment by BeauMcMurray** [comment]
Damn I was hoping that would fix my issue with the installer. I'm using the correct file now, and have updated the config.plist. 

Panic logs mention the following (kernel extensions in backtrace):
com.apple.iokit.IOPCIFamily
com.apple.driver.AppleACPIPlatform
com.apple.driver.AppleIntelSKLGraphicsFramebuffer

Any ideas where I should start troubleshooting? Thanks for the quick reply btw.

**Comment by midi1996** [comment]
you did not prepare your DeviceProperties section properly (also I updated the guide).

**Comment by BeauMcMurray** [comment]
Mine is an i7 model with the HD530.

DeviceProperties are as follows:
PciRoot(0x0)/Pci(0x1b,0x0)
No children

PciRoot(0x0)/Pci(0x2,0x0)
framebuffer-patch-enable 1 (Number)
framebuffer-stolenmem 00003001 (Data)
framebuffer-fbmem 00009000 (Data)

Device-Id and AAPL,ig-platform-id have not been added.

PciRoot(0x0)/Pci(0x1f,0x3) (What's this one for?)
layout-id 29 (Number)

**Comment by midi1996** [comment]
Did you change the Video Memory in UEFI Setup to 512MB? Are you using WhateverGreen (and it's properly added to the config)?

**Comment by BeauMcMurray** [comment]
Yes 512MB confirmed. I am using whatevergreen, will double check config tomorrow, but I remember seeing it there (added automatically when propertree scanned the kexts).

**Comment by BeauMcMurray** [comment]
Confirmed WhateverGreen is properly added to the config (it's the last entry). Also have tried using an older version with no luck.

I've attached the panic log and my config.plist for reference.

[panic-2020-07-03-210519.txt](https://github.com/midi1996/P50-opencore-hackintosh/files/4869853/panic-2020-07-03-210519.txt)
[config.plist.zip](https://github.com/midi1996/P50-opencore-hackintosh/files/4869854/config.plist.zip)

**Comment by midi1996** [comment]
Sorry for being late, I had many irl stuff to deal with. So try adding this in your iGPU Properties section:

| Key | Type | Value |
| ---- | --- | --- |
| `AAPL,ig-platform-id` | Data | `00001B19` |
