### ISSUE TITLE
Graphics Issues

### ISSUE THREAD

**Issue by walstib2** [midi1996/P50-opencore-hackintosh#3]
First – Thanks for the guide.  This is the first laptop I’ve tackled and the first hack with open core. 

Got basically the same laptop as you but have the “4k – non touch screen”.

Working through the install process and was able to get 10.15.5 installed with basic functionality – 1st problem to tackle was graphics – Added information below to config.plist and Laptop seems to hang right before apple and progress bar comes on screen. 
![image](https://user-images.githubusercontent.com/52056628/87595499-a1dd2f00-c6bc-11ea-82d0-a703183988f5.png)

Removed the single line : device-id = 16190000. And it boots all the way to the desktop with bad graphics – any ideas?

**Comment by midi1996** [comment]
the device-id you're showing me in the screenshot is wrong. Also since you said you have the same laptop with 4K display, I'll assume it's a Xeon CPU with Intel HP P530.
Try these values

![image](https://user-images.githubusercontent.com/4874726/87601593-4d9e7300-c6ed-11ea-8976-88406828b380.png)

I would also recommend that you use [ProperTree](https://github.com/corpnewt/ProperTree) as it is crossplatform and does not have Number/Real issue as Xcode (or potentially PlistEdit Pro, which is also paid and macOS only).

**Comment by walstib2** [comment]
Thanks for the quick reply - usually I do use ProperTree,  I used PlistEditPro to edit a backup file real quick and send a picture and made a typo.  Tried the new values and have the same issue as before - Here is proof of no typo and a screengrab of where it hangs   
<img width="1019" alt="screenshot_13" src="https://user-images.githubusercontent.com/52056628/87605860-9f340700-c6c7-11ea-8837-038cac326075.png">

![IMG_20200715_180839](https://user-images.githubusercontent.com/52056628/87605976-e621fc80-c6c7-11ea-83b0-ea7d4ffead7f.jpg)

Tried again with the original  device-id of 16190000 just to make sure I didn't have a typo and have the same results
<img width="880" alt="screenshot_14" src="https://user-images.githubusercontent.com/52056628/87606081-1e293f80-c6c8-11ea-9b97-56ead4be1e8e.png">
 
I do notice that seems it is not locked completely up -  when I hit enter or other hotkeys the hard drive light flashes for a few seconds then stops.

**Comment by walstib2** [comment]
Well... Looks like mine is somehow different... Tried a clean install with the same results - Brings to mind Einstein's definition of insanity ...

**Comment by midi1996** [comment]
I updated the guide for 4K displays, not sure if that would fix it for you. I'm closing this issue as it hasn't been active.
