### ISSUE TITLE
Lenovo P50 Hackintosh No Audio from Speakers And Other Issues

### ISSUE THREAD

**Issue by Lego737** [midi1996/P50-opencore-hackintosh#6]
Hello, I have successfully hacked my Lenovo P50 using Clover BootLoader. However, there are some things that I have not worked out. Those things are my audio, and my lower trackpad buttons. All of these things listed here work under windows 10, just not macOS Catalina. 

Are these able to be fixed using Clover? I want to use this as my main "HackBook Pro."

**Comment by midi1996** [comment]
I do not support clover and i dont really see why would you. Switch to opencore.
