### ISSUE TITLE
Anther solution for video output

### ISSUE THREAD

**Issue by AndyTQ** [midi1996/P50-opencore-hackintosh#7]
I noticed that in the discussion section "What's not working" in readme file, solution for video output is written as:
_**Solutions:**
  AirPlay
  3rd party screen streaming
  USB to HDMI adapters (not tested)_

I want to add that I previously tested video output via eGPU @ TB3 and it worked on Thinkpad P51. It was tested over 2 years ago (late 2019) on Catalina, but I think it should theoretically be possible to still make it working on Monterey for both P51 and P50 (since they have extremely similar hardware). It was very stable on Catalina. I no longer have an eGPU so I am unable to test it on Monterey anymore. You need to do the following to get it work:
- Change SMBIOS platform to iMacPro1, 1 (This is specific for my RX5700XT, as mentioned in https://www.tonymacx86.com/threads/rx-5700-xt-compatibility.285798/.) For older cards such as RX 570/580, you probably won't need to do this, according to https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme).
- Add boot flag agdpmod=pikera
- **Disable iGPU in BIOS,** i.e. changing hybrid graphics to discrete graphics.
- As always, plug in the tb3 port BEFORE booting.

The internal screen will be disabled in this case, and the P51/50 will function like a desktop machine. Unfortunately, I can't get eGPU working if I don't turn off the iGPU (and therefore, the internal screen).

Hope this information can be useful for some people who want to attempt a smoother video output to monitors. 
![71485560-a9e88680-27df-11ea-80b9-f53fbbbd05d7](https://user-images.githubusercontent.com/27390240/164914890-1cc09a8c-e68c-43ce-ba6b-05860979416f.jpeg)

**Comment by midi1996** [comment]
I mean this is a solution but you'll have to get a whole GPU and setup with it to get it working, which is not ideal haha. Sure it will be much more performant but that's a really expensive solution, my point there was having multiple displays from the iGPU directly, which is not possible because the iGPU has only one output wired into it which is the internal display. Thanks for sharing, and I think sleep will be obviously broken because of this.

**Comment by AndyTQ** [comment]
Wow, thats a quick reply. Yeah this is definitely an very expensive solution (eGPU + GPU). It is not ideal to buy a whole GPU + eGPU just for a 4-year-old hackintosh laptop haha. I added this issue to share some information with potential people who have an eGPU around already.
